### ISSUE TITLE
M3DB Out Of Order Writes

### ISSUE THREAD

**Issue by justinjc** [m3db/proposal#5]
Design doc:
https://docs.google.com/document/d/1j1aC7-YD3PqyDPyJIpEQFaAbcD6lToGP3_YHngjD3HQ/edit

cc @prateek @robskillington @richardartoul

**Comment by robskillington** [comment]
LGTM @justinjc, please export as a markdown document and submit a PR to add it to the repository as per https://github.com/m3db/proposal#process. 👏

**Comment by asafm** [comment]
For future readers, the following proposal seems to be related to current proposal: https://github.com/m3db/proposal/issues/16
